### ISSUE TITLE
Did you test this model on normal ner tasks?

### ISSUE THREAD

**Issue by drxmy** [yhcc/CNN_Nested_NER#2]
Great work! 
Just wondering its performance on normal ner tasks, like unnested entity.

**Comment by yhcc** [comment]
Thanks for your attention. It can also enhance the performance of flat NER tasks, but not as good as in the nested scenario. In widely used conll2003 and OntoNotes, the enhancement is about 0.2 on F1.

**Comment by drxmy** [comment]
Thank you!
