### ISSUE TITLE
能否用来处理中文？

### ISSUE THREAD

**Issue by nlper01** [yhcc/CNN_Nested_NER#8]
你好，这个模型适用于中文吗？此外，是否只适用于嵌套实体抽取，如果数据集中同时包含扁平和嵌套实体，扁平实体也能识别吗？

**Comment by wind1312** [comment]
> 你好，这个模型适用于中文吗？此外，是否只适用于嵌套实体抽取，如果数据集中同时包含扁平和嵌套实体，扁平实体也能识别吗？

请问适用中文吗
