### ISSUE TITLE
代码中的bpes表示的什么？

### ISSUE THREAD

**Issue by nlper01** [yhcc/CNN_Nested_NER#9]
` assert len(bpes)<=512, len(bpes)`  
我已经把我的数据中长度超过400的截断了，为什么这里还会报错？
这里的bpes表示的什么？

**Comment by ShaoZhangHao** [comment]
请问你知道bpes代表什么意思了吗

**Comment by nlper01** [comment]
后面把代码调通了，就没追究这个问题了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhcc/CNN_Nested_NER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月26日(星期天) 下午3:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yhcc/CNN_Nested_NER] 代码中的bpes表示的什么？ (Issue #9)





 
请问你知道bpes代表什么意思了吗
